# Generated by cpputils-cmake.
include /home/rayzhang/perl_code/stereo-dso/build/CMakeFiles/dso.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES}  -S ${CHK_SOURCES}